export const Medicines = [
    {
      id: 1,
      title: "Crocin",
      description: "for pain relief",
      price: "20",
      img: "https://www.pexels.com/photo/thermometer-on-medical-pills-139398/",
      quantity: 1,
    },
    {
      id: 2,
      title: "Glimstar M1",
      description: "for pain relief",
      price: "30",
      img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 3,
      title: "Olmi d20",
      description: "for pain relief",
      price: "40",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Myocilz50",
      description: "for pain relief",
      price: "100",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Telsimartin20",
      description: "for pain relief",
      price: "250",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 6,
      title: "Neosprin",
      description: "for pain relief",
      price: "350",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "GlimyM3",
      description: "for pain relief",
      price: "127",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 8,
      title: "Depran5",
      description: "for pain relief",
      price: "905",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "AddNa5",
      description: "for pain relief",
      price: "500",
      img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
  ];